#ifndef CONFIG_H
#define CONFIG_H

#define BUFFER_SIZE 16
#define BUFFER_SIZE_GRID 100

#define PWD "/Users/branislav/Documents/Code/FRI/battleships"
//#define PWD "/home/blazek10/battleships"
//#define PWD "/home/adieediee/battleships/battleships"

#define PATH_CLIENT_1_SERVER "/PC_PIPE_CLIENT_1_SERVER"
#define PATH_CLIENT_2_SERVER "/PC_PIPE_CLIENT_2_SERVER"
#define PATH_SERVER_CLIENT_1 "/PC_PIPE_SERVER_CLIENT_1"
#define PATH_SERVER_CLIENT_2 "/PC_PIPE_SERVER_CLIENT_2"
#define PATH_HANDSHAKE_CLIENT_SERVER "/PC_PIPE_HANDSHAKE_CLIENT_SERVER"
#define PATH_HANDSHAKE_SERVER_CLIENT "/PC_PIPE_HANDSHAKE_SERVER_CLIENT"


#define PIPE_CLIENT_1_SERVER PWD PATH_CLIENT_1_SERVER
#define PIPE_SERVER_CLIENT_1 PWD PATH_SERVER_CLIENT_1
#define PIPE_CLIENT_2_SERVER PWD PATH_CLIENT_2_SERVER
#define PIPE_SERVER_CLIENT_2 PWD PATH_SERVER_CLIENT_2
#define PIPE_HANDSHAKE_CLIENT_SERVER PWD PATH_HANDSHAKE_CLIENT_SERVER
#define PIPE_HANDSHAKE_SERVER_CLIENT PWD PATH_HANDSHAKE_SERVER_CLIENT

#endif

